### ISSUE TITLE
Bug in reader.GetTrack

### ISSUE THREAD

**Issue by cristobal-sifon** [Kambrian/HBT2#7]
```
  subid=find(self.LoadSubhalos(isnap, 'TrackId')==trackId)[0]
Traceback (most recent call last):
  File "subhalo_history.py", line 57, in <module>
    reader.GetTrack(3)
  File "/gpfs/data/durham/dc-sifo1/git/HBTplus/toolbox/HBTReader.py", line 256, in GetTrack
    for isnap in range(snapbirth, self.MaxSnap+1):
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by Kambrian** [comment]
I cannot reproduce the issue. Can you provide more information?
